# Generated by Django 6.0.6 on 2026-06-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subsystem', models.CharField(blank=True, choices=[('ANGLOPHONE', 'Anglophone'), ('FRANCOPHONE', 'Francophone')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=200, unique=True, verbose_name='Subject Name')),
                ('subjectCode', models.CharField(max_length=20, verbose_name='Subject Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('department', models.CharField(max_length=100, null=True, verbose_name='Department')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sub_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sujetsExam.subject')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sujetsExam.examtype')),
                ('subjectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sujetsExam.subject')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
