# Generated by Django 6.0.6 on 2026-06-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sujetsExam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='sub_name',
            new_name='subjectName',
        ),
    ]
