# Generated by Django 6.0.6 on 2026-06-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sujetsExam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chap_name', models.CharField(max_length=100)),
                ('chapter_number', models.PositiveIntegerField(verbose_name='Chapter Number')),
                ('description', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chap_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjectChapters.chapter')),
                ('sub_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sujetsExam.subject')),
            ],
        ),
    ]
