# Generated by Django 6.0.6 on 2026-06-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sujetsExam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100, verbose_name='option Name')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Department')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('option_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filiereClass.optionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filiereClass.level')),
                ('sub_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sujetsExam.subject')),
            ],
        ),
    ]
