# Generated by Django 6.0.7 on 2026-07-12 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0001_initial"),
        ("subjectChapters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exercises",
                to="subjectChapters.chapter",
            ),
        ),
    ]
