# Generated by Django 6.0.7 on 2026-07-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
