# Generated by Django 6.0.6 on 2026-06-23 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sujetsExam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_title', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('correct_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paper_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sujetsExam.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('correct_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corrections.correction')),
            ],
        ),
    ]
