# Generated by Django 6.0.6 on 2026-06-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corrections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correction',
            name='subject_name',
        ),
    ]
